# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

stages:

  - stage: Build
    display: Build
    jobs:

    - job: Linux 
      pool: 
        vmImage: 'ubuntu-latest'
      steps:
        - task: NodeTool@0
          displayName: Node install
          inputs:
            versionSpec: '6.x'
        - script: npm install && npm build 

    - job: MacOS
      pool: 
        vmImage: 'macOS-latest' 
      steps:
        - task: NodeTool@0Linuxstall
          displayName: Node install
          inputs:
            versionSpec: '6.x'
        - script: npm install && npm build